version: '2.4'
services:
  ors-app:
    container_name: ors-app
    ports:
      - "8080:5631"
      - "9001:9001"
        #image: openrouteservice/openrouteservice:v7.1.1
    user: 0000:0000
      #entrypoint : "/home/ors/entrypoint.sh"
      #command: 
      #- "/home/ors"
    build:
      context: .
      dockerfile : Dockerfile
      args:
        PORT: 5631
#        ORS_CONFIG: ./openrouteservice/src/main/resources/ors-config-sample.json
#        OSM_FILE: ./openrouteservice/src/main/files/heidelberg.osm.gz
#volumes:
      #- ./graphs:/home/ors/ors-core/data/graphs
      #- ./elevation_cache:/home/ors/ors-core/data/elevation_cache
      #- ./logs/ors:/home/ors/ors-core/logs/ors
      #- ./logs/tomcat:/home/ors/tomcat/logs
      #- ./conf:/home/ors/ors-conf
      #- ./quebec-latest.osm.pbf:/home/ors/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=FALSE  # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - PORT=5631
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseG1GC -XX:+ScavengeBeforeFullGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
